kid1: |
  -----BEGIN PUBLIC KEY-----
  MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAx+53mkrgbrTll6PnT1rD
  9lcTREJWV8sI8OyiRmjA7CT//XdWpLZt8t6vPmdWcjEhNwHEufNGYrX0t5kldQl4
  o0UljY5+Z8l9U9MUcRAXX9bzqp3opZb+x/EEwUmekibyaFXBqau3i1KPRCR/gwe5
  SN4l3SgFuJX/ZV9jcLGX5PNqMVCw1NXxISHL2ZO4Rq+02O+wyluVviZVSPkzZUAL
  CSlEdJEEP89M7g8QGGHtCFXUpxRcIhs49+FR6dtINxLb/e8ZJtCxkBz18Y7O7xHr
  95NSFxJ3BgdAXI/Eh4JoB/osxu05EsLrN6peEWaLtShpv0pyDhJo2Pm7dYThwV8j
  CwIDAQAB
  -----END PUBLIC KEY-----
