repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.5
    hooks:
      - id: ruff
  - repo: local
    hooks:
      - id: regression-tests
        name: regression tests
        entry: pytest tests/observability -q
        language: system
        pass_filenames: false
