repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.7
    hooks:
      - id: ruff
        name: ruff (fix on core)
        entry: ruff check --fix
        args: [alpha]
        language_version: python3
      - id: ruff-format
        name: ruff format (core)
        entry: ruff format
        args: [alpha]
        language_version: python3
  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
# Optional: enable locally if you want auto-import sorting
# - repo: https://github.com/PyCQA/isort
#   rev: 5.13.2
#   hooks:
#     - id: isort
#       name: isort (fix on core)
#       args: [alpha]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
exclude: '^(artifacts|telemetry|logs|\.venv|\.ruff_cache|\.pytest_cache)/'
