[tool.black]
line-length = 100
target-version = ["py312"]

[tool.isort]
profile = "black"
line_length = 100
py_version = 312
skip = ["artifacts", "telemetry", "logs", ".venv", ".pytest_cache", ".ruff_cache"]

[tool.ruff]
line-length = 100
target-version = "py312"
exclude = ["artifacts", "telemetry", "logs", "scripts", "tests", ".venv", ".pytest_cache", ".ruff_cache"]
lint.select = ["E", "F"]
lint.ignore = []

# Tests often use convenience imports and multi-import lines for fixtures/mocks.
# Keep source strict, relax tests to avoid noise blocking CI.
[tool.ruff.lint.per-file-ignores]
"tests/**/*" = ["F401", "E401"]

