name: gates
on:
  pull_request:
    branches: ["*"]
permissions:
  contents: read
jobs:
  gatekeeper:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
      - run: python -m pip install -U pip
      - run: pip install -r requirements-dev.txt
      - name: pre-commit
        run: pre-commit run --show-diff-on-failure --all-files
      - name: pytest
        env:
          PYTHONPATH: .
        run: pytest -q
      - name: eval baseline vs optimized
        env:
          PYTHONPATH: .
        run: |
          python -m alpha.eval.harness --dataset datasets/mvp_golden.jsonl --seed 42 --compare-baseline
          cp artifacts/eval/router_compare.json artifacts/eval/router_compare_run1.json
      - name: determinism check
        env:
          PYTHONPATH: .
        run: |
          python -m alpha.eval.harness --dataset datasets/mvp_golden.jsonl --seed 42 --compare-baseline
          python - <<'PY'
import json, sys
from pathlib import Path
from alpha.core.metrics import determinism_hash, determinism_verdict
root = Path('artifacts/eval')
h1 = determinism_hash(root / 'router_compare_run1.json')
h2 = determinism_hash(root / 'router_compare.json')
verdict = determinism_verdict(h1, h2)
summary = json.load((root / 'summary.json').open())
summary['determinism'] = verdict
json.dump(summary, (root / 'summary.json').open('w'), indent=2, sort_keys=True)
print('determinism', verdict)
if not verdict:
    sys.exit(1)
PY
      - name: enforce gates
        run: |
          python - <<'PY'
import json, sys
with open('artifacts/eval/summary.json') as fh:
    summary = json.load(fh)
metrics = summary.get('metrics', {})
if not (
    metrics.get('em', 0) >= 0.85 and
    metrics.get('p95_ms', 0) <= 750 and
    metrics.get('p99_ms', 0) <= 1200 and
    summary.get('token_savings_pct', 0) >= 0.15 and
    summary.get('determinism')
):
    print('gate failed', summary)
    sys.exit(1)
PY
      - uses: actions/upload-artifact@v4
        with:
          name: eval-artifacts
          path: artifacts/eval
