name: gates

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  gates:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install deps
        run: |
          python -m pip install -U pip
          pip install -r requirements-dev.txt || pip install "pytest>=8,<9"
          pip install ruff==0.5.7 pre-commit==4.3.0

      - name: Pre-commit (formatting & YAML checks)
        run: pre-commit run --all-files

      - name: Unit tests
        run: pytest -q

      - name: Eval (compare-baseline) and write artifacts
        run: |
          mkdir -p artifacts/eval
          python -m alpha.eval.harness --dataset datasets/mvp_golden.jsonl --seed 42 --compare-baseline

      - name: Upload eval artifacts
        uses: actions/upload-artifact@v4
        with:
          name: eval-artifacts
          path: artifacts/eval/
