name: gates
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  reliability:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install -U pip
          pip install -r requirements-dev.txt
          pip install pytest-json-report
      - name: Run reliability tests
        env:
          SLO_REPORT: artifacts/reliability.json
        run: |
          mkdir -p artifacts
          pytest -q tests/reliability -k "retry or breaker" --json-report --json-report-file=artifacts/reliability.json || true
      - name: Enforce reliability SLO
        run: |
          python -m alpha.reliability.slo artifacts/reliability.json
