name: gates
on:
  pull_request:

jobs:
  gates:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt pytest-json-report

      - name: "Reliability SLO: run tests"
        run: |
          mkdir -p artifacts
          pytest -q tests/reliability -k "retry or breaker" \
            --json-report --json-report-file=artifacts/reliability.json || true

      - name: "Reliability SLO: enforce"
        run: python -m alpha.reliability.slo artifacts/reliability.json

      - name: "Metrics exporter perf"
        run: |
          pytest -q tests/metrics/test_aggregator.py -q

      - name: Upload reliability artifacts
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: reliability
          path: artifacts/
