name: Nightly sweep + artifacts
on:
  workflow_dispatch: {}
  schedule:
    - cron: "17 7 * * *"  # daily 07:17 UTC
jobs:
  nightly:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.12" }
      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements-dev.txt', 'constraints.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install deps
        run: |
          python -m pip install -U pip
          pip install -r requirements-dev.txt -c constraints.txt
      - name: Nightly sweep (deterministic)
        env:
          ALPHA_DETERMINISM: "1"
          GIT_COMMIT_SHA: ${{ github.sha }}
        run: |
          python -m alpha.cli run --queries-file docs/queries.sample.txt --regions US --seed 1234 --plan-only
          python scripts/telemetry_leaderboard.py --paths telemetry/*.jsonl --format all || true
          python scripts/overview_md.py || true
      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: nightly-artifacts
          path: |
            artifacts/**
            telemetry/**
