name: nightly
on:
  schedule:
    - cron: "0 7 * * *"
  workflow_dispatch:

jobs:
  bundle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run: python -m pip install -U pip
      - run: pip install "pytest>=8,<9"
      - run: python scripts/telemetry_leaderboard.py --paths telemetry/*.jsonl --topk 5 --format md --out artifacts/leaderboard.md
      - run: python scripts/bundle_artifacts.py
      - uses: actions/upload-artifact@v4
        with:
          name: nightly-bundle
          path: artifacts/bundles/*.zip
          if-no-files-found: ignore
