name: Build & attach release artifacts
on:
  push:
    tags:
      - "v*"
jobs:
  build-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.12" }
      - name: Build sdist/wheel
        run: |
          python -m pip install --upgrade pip build
          python -m build
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: alpha-solver-dist
          path: dist/*
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

