name: reliability-slo

on:
  push:
    branches: [ main ]
  pull_request:

permissions:
  contents: read

jobs:
  reliability-slo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt', 'constraints.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install deps
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt -c constraints.txt
          pip install -r requirements-test.txt -c constraints.txt
          pip install pytest -c constraints.txt
      - name: Run reliability SLO tests
        env:
          PYTHONPATH: .
          SLO_REPORT: slo_report.json
        run: |
          pytest tests/reliability/test_retry_and_breaker.py -q
          python alpha/reliability/slo.py slo_report.json
