name: tests
on:
  push:
    branches: [ main ]
  pull_request:
permissions:
  contents: read
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
      - run: python -m pip install -U pip
      - run: pip install -r requirements-dev.txt || pip install "pytest>=8,<9"
      - name: Preflight
        run: |
          python scripts/preflight.py > preflight.json
          exit_code=$?
          if [ "${ALPHA_CI_PREFLIGHT_STRICT:-0}" = "1" ] && [ $exit_code -ne 0 ]; then
            exit $exit_code
          fi
          exit 0
      - uses: actions/upload-artifact@v4
        with:
          name: preflight
          path: preflight.json
      - env:
          PYTHONPATH: .
        run: python -m pytest -q
      - name: Packaging smoke build (non-blocking)
        if: always()
        run: |
          python -m pip install --upgrade pip build
          python -m build
        continue-on-error: true
      - if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-artifacts
          path: |
            artifacts/**
            tests/**/diff*.txt
      - name: Lint (ruff only)
        run: |
          pip install ruff==0.5.7
          ruff check alpha
